---
# tasks file for setUpYADMAndGit

- block:

    - name: Installing YADM
      ansible.builtin.apt:
          force_apt_get: yes
          name: yadm
          state: present
      register: yadm_ouptut
      tags:
          - install_yadm

    - ansible.builtin.debug:
        var: yadm_ouptut 

    - name: Adding yadm push url   
      ansible.builtin.command:
          cmd: 
            yadm remote origin {{yadm_push_url}}
      when: yadm_ouptut.changed != false

  rescue:
      - ansible.builtin.debug:
          msg: "YADM already insatalled"


- block:

    - name: Installing Git
      ansible.builtin.apt:
          force_apt_get: yes
          name: git
          state: latest 
      register: git_output
      tags:
          - install_git
    
    - block:

        - name: Adding git config name
          community.general.git_config:
              name: user.name
              scope: global
              repo: ~/.gitconfig
              value: "{{git_user_name}}" 

        - name: Adding git config email
          community.general.git_config:
              name: user.email
              scope: global
              value : "{{git_email}}"
         
      when: git_output.changed == false
      

