---
# tasks file for setUpYADMAndGit

- name: Gather package facts
  ansible.builtin.package_facts:
        manager: auto

- block: 
    - name: Installing YADM
      ansible.builtin.apt:
          force_apt_get: yes
          name: yadm
          state: present
      register: yadm_ouptut
      tags:
          - install_yadm

    - name: Check if yadm repo exits
      stat:
          path: /home/piiithagorus/.local/share/yadm/repo.git/
      register: yadm_repo_found

    - name: Clone yadm repo
      ansible.builtin.shell:
          cmd: yadm clone {{yadm_clone_url}}
      when: not yadm_repo_found['stat']['exists']


    - name: Add yadm pushUrl   
      community.general.git_config:
            name: remote.origin.pushurl
            scope: local
            repo: /home/piiithagorus/.local/share/yadm/repo.git/
            value: "{{yadm_push_url}}"
      when: " 'yadm' in ansible_facts.packages"


- block: 
    - name: Installing Git
      ansible.builtin.apt:
          force_apt_get: yes
          name: git
          state: latest 
      register: git_output
      tags:
          - install_git

    - name: Configure gitconfig 
      ansible.builtin.template:
         src: gitconfig.j2
         dest: "/home/piiithagorus/.gitconfig"
         force: yes
         mode: 0767
      when: " 'git' in ansible_facts.packages"
