---
# tasks file for setUpYADMAndGit

- name: Gather package facts
  ansible.builtin.package_facts:
        manager: auto

- name: Installing packages for Debian_based
  include_tasks:
      file: debian_based.yml
  when: ansible_os_family == "Debian"
    

- name: Installing packages for Arch_based 
  include_tasks:
      file: arch_based.yml
  when: ansible_os_family == "Archlinux"


- name: Installing packages for RedHat_based 
  include_tasks:
      file: redhat_based.yml
  when: ansible_os_family == "RedHat"


- block: 
    - name: Make yadm directory
      ansible.builtin.file:
         dest: "/home/{{user_name}}/.local/share/yadm"
         mode: 0767

    - name: Clone yadm repo
      ansible.builtin.git:
          repo: "{{yadm_clone_url}}"
          accept_hostkey: yes
          dest: "/home/{{user_name}}/.local/share/yadm"
          separate_git_dir: "/home/{{user_name}}/.local/share/yadm/repo.git"

- block: 
    - name: Configure gitconfig 
      ansible.builtin.template:
         src: gitconfig.j2
         dest: "/home/{{user_name}}/.gitconfig"
         force: yes
         mode: 0767
