---
# tasks file for setUpYADMAndGit

- name: Gather package facts
  ansible.builtin.package_facts:
        manager: auto

- name: Installing packages for Debian_based
  include_tasks:
      file: debian_based.yml
  when: ansible_os_family == "Debian"
    

- name: Installing packages for Arch_based 
  include_tasks:
      file: redhat_based.yml
  when: ansible_os_family == "Archlinux"


- name: Installing packages for RedHat_based 
  include_tasks:
      file: debian_based.yml
  when: ansible_os_family == "RedHat"

- block: 
    - name: Check if yadm repo exits
      stat:
          path: /home/piiithagorus/.local/share/yadm/repo.git/
      register: yadm_repo_found

    - name: Clone yadm repo
      ansible.builtin.shell:
          cmd: yadm clone {{yadm_clone_url}}
      when: not yadm_repo_found['stat']['exists']


    - name: Add yadm pushUrl   
      community.general.git_config:
            name: remote.origin.pushurl
            scope: local
            repo: /home/piiithagorus/.local/share/yadm/repo.git/
            value: "{{yadm_push_url}}"
      when: " 'yadm' in ansible_facts.packages"


- block: 
    - name: Configure gitconfig 
      ansible.builtin.template:
         src: gitconfig.j2
         dest: "/home/piiithagorus/.gitconfig"
         force: yes
         mode: 0767
